"""Public contracts for the Loushang operational ontology kernel.

The semantic write authority is the append-only :class:`FactStore`.  Object,
property, and link graphs are read-only projections and are intentionally not
published as a second mutation surface.
"""

from loushang.ontology.facts import (
    FACT_BATCH_FORMAT,
    FACT_FORMAT,
    AssertionKind,
    FactAssertion,
    FactBatch,
    FactBatchConflictError,
    FactCommit,
    FactProjection,
    FactProjectionDiagnostic,
    FactProjectionError,
    FactReadStore,
    FactRecord,
    FactStore,
    FactValidationError,
    LinkAssertion,
    MemoryFactStore,
    ObjectAssertion,
    PropertyAssertion,
    StoredFact,
    project_facts,
)
from loushang.ontology.query import QueryBuilder, QueryRequest, QueryResult
from loushang.ontology.schema import (
    SCHEMA_DIFF_FORMAT,
    SCHEMA_FORMAT,
    ChangeImpact,
    CompiledInterfaceTypeDefinition,
    CompiledLinkTypeDefinition,
    CompiledObjectTypeDefinition,
    CompiledOntologySchema,
    CompiledPropertyDefinition,
    InterfaceTypeDefinition,
    LinkCardinality,
    LinkTypeDefinition,
    ObjectTypeDefinition,
    OntologyCompiler,
    OntologyPackageDraft,
    PropertyDefinition,
    SchemaChange,
    SchemaCompilationError,
    SchemaDiagnostic,
    SchemaDiff,
    SchemaLineageError,
    SchemaVersion,
    ValueType,
    compare_schemas,
)

__all__ = [
    "FACT_BATCH_FORMAT",
    "FACT_FORMAT",
    "SCHEMA_DIFF_FORMAT",
    "SCHEMA_FORMAT",
    "AssertionKind",
    "ChangeImpact",
    "CompiledInterfaceTypeDefinition",
    "CompiledLinkTypeDefinition",
    "CompiledObjectTypeDefinition",
    "CompiledOntologySchema",
    "CompiledPropertyDefinition",
    "FactAssertion",
    "FactBatch",
    "FactBatchConflictError",
    "FactCommit",
    "FactProjection",
    "FactProjectionDiagnostic",
    "FactProjectionError",
    "FactReadStore",
    "FactRecord",
    "FactStore",
    "FactValidationError",
    "InterfaceTypeDefinition",
    "LinkAssertion",
    "LinkCardinality",
    "LinkTypeDefinition",
    "MemoryFactStore",
    "ObjectAssertion",
    "ObjectTypeDefinition",
    "OntologyCompiler",
    "OntologyPackageDraft",
    "PropertyAssertion",
    "PropertyDefinition",
    "QueryBuilder",
    "QueryRequest",
    "QueryResult",
    "SchemaChange",
    "SchemaCompilationError",
    "SchemaDiagnostic",
    "SchemaDiff",
    "SchemaLineageError",
    "SchemaVersion",
    "StoredFact",
    "ValueType",
    "compare_schemas",
    "project_facts",
]
