"""Public contracts for the Loushang operational ontology kernel.

The semantic write authority is the append-only :class:`FactStore`. Object,
property, and link graphs are immutable, replaceable snapshots and never a
second business-mutation surface.
"""

from loushang.ontology.facts import (
    FACT_BATCH_FORMAT,
    FACT_FORMAT,
    AssertionKind,
    FactAssertion,
    FactBatch,
    FactBatchConflictError,
    FactCommit,
    FactReadStore,
    FactRecord,
    FactSelection,
    FactStore,
    FactValidationError,
    LinkAssertion,
    ObjectAssertion,
    PropertyAssertion,
    StoredFact,
)
from loushang.ontology.projection import (
    ProjectedLink,
    ProjectedObject,
    ProjectedProperty,
    ProjectionDiagnostic,
    ProjectionFreshness,
    ProjectionFreshnessStatus,
    ProjectionMaterializationError,
    ProjectionReadStore,
    ProjectionSnapshot,
    ProjectionState,
    ProjectionStore,
    ProjectionUnavailableError,
    evaluate_projection_freshness,
    materialize_projection,
)
from loushang.ontology.query import QueryBuilder, QueryRequest, QueryResult
from loushang.ontology.schema import (
    SCHEMA_DIFF_FORMAT,
    SCHEMA_FORMAT,
    ChangeImpact,
    CompiledInterfaceTypeDefinition,
    CompiledLinkTypeDefinition,
    CompiledObjectTypeDefinition,
    CompiledOntologySchema,
    CompiledPropertyDefinition,
    InterfaceTypeDefinition,
    LinkCardinality,
    LinkTypeDefinition,
    ObjectTypeDefinition,
    OntologyCompiler,
    OntologyPackageDraft,
    PropertyDefinition,
    SchemaChange,
    SchemaCompilationError,
    SchemaDiagnostic,
    SchemaDiff,
    SchemaLineageError,
    SchemaVersion,
    StateAuthority,
    ValueType,
    compare_schemas,
)
from loushang.ontology.storage import MemoryFactStore, MemoryProjectionStore

__all__ = [
    "FACT_BATCH_FORMAT",
    "FACT_FORMAT",
    "SCHEMA_DIFF_FORMAT",
    "SCHEMA_FORMAT",
    "AssertionKind",
    "ChangeImpact",
    "CompiledInterfaceTypeDefinition",
    "CompiledLinkTypeDefinition",
    "CompiledObjectTypeDefinition",
    "CompiledOntologySchema",
    "CompiledPropertyDefinition",
    "FactAssertion",
    "FactBatch",
    "FactBatchConflictError",
    "FactCommit",
    "FactReadStore",
    "FactRecord",
    "FactSelection",
    "FactStore",
    "FactValidationError",
    "InterfaceTypeDefinition",
    "LinkAssertion",
    "LinkCardinality",
    "LinkTypeDefinition",
    "MemoryFactStore",
    "MemoryProjectionStore",
    "ObjectAssertion",
    "ObjectTypeDefinition",
    "OntologyCompiler",
    "OntologyPackageDraft",
    "PropertyAssertion",
    "PropertyDefinition",
    "ProjectedLink",
    "ProjectedObject",
    "ProjectedProperty",
    "ProjectionDiagnostic",
    "ProjectionFreshness",
    "ProjectionFreshnessStatus",
    "ProjectionMaterializationError",
    "ProjectionReadStore",
    "ProjectionSnapshot",
    "ProjectionState",
    "ProjectionStore",
    "ProjectionUnavailableError",
    "QueryBuilder",
    "QueryRequest",
    "QueryResult",
    "SchemaChange",
    "SchemaCompilationError",
    "SchemaDiagnostic",
    "SchemaDiff",
    "SchemaLineageError",
    "SchemaVersion",
    "StateAuthority",
    "StoredFact",
    "ValueType",
    "compare_schemas",
    "evaluate_projection_freshness",
    "materialize_projection",
]
