"""Channel boundary protocol primitives."""

from loushang.channel.host import (
    ChannelDelivery,
    ChannelDeliveryListener,
    ChannelHost,
    ChannelHostPort,
    ChannelUnsubscribe,
)
from loushang.channel.json_codec import (
    channel_envelope_from_json,
    channel_envelope_to_json,
)
from loushang.channel.json_projection import (
    ChannelJsonProjectionError,
    project_channel_value,
)
from loushang.channel.jsonl_command_host import (
    JsonlCommand,
    JsonlCommandErrorListener,
    JsonlCommandHost,
    JsonlCommandHostError,
    JsonlCommandHostErrorKind,
    JsonlCommandHostErrorReason,
    JsonlCommandPort,
)
from loushang.channel.jsonl_command_router import (
    JsonlCommandHandler,
    JsonlCommandRoute,
    JsonlCommandRouter,
    JsonlUnsupportedCommandHandler,
)
from loushang.channel.product_host import (
    ProductHostAction,
    ProductHostActionType,
    ProductHostAdapter,
    ProductHostLifecycle,
    ProductHostRuntime,
    ProductHostState,
    ProductHostStateReader,
    ProductHostStreams,
    ProductHostTaskTracker,
    dispatch_product_host_action,
    dispose_product_host,
    normalize_product_host_action,
)
from loushang.channel.remote_ui import RemoteUiContext
from loushang.channel.rpc_jsonl import (
    ChannelError,
    ChannelEventDelivery,
    ChannelOperationAccepted,
    ChannelOperationCancelled,
    ChannelOperationCancelRequest,
    ChannelOperationRequest,
    ChannelRpcFrame,
    ChannelRpcFrameKind,
    decode_rpc_jsonl_frame,
    encode_rpc_jsonl_frame,
    rpc_jsonl_frame_from_json,
    rpc_jsonl_frame_to_json,
)
from loushang.channel.stdout_guard import (
    flush_raw_stdout,
    is_stdout_taken_over,
    restore_stdout,
    stdout_guard,
    take_over_stdout,
    write_raw_stdout,
)
from loushang.channel.types import (
    ChannelEndpoint,
    ChannelEnvelope,
    ChannelEnvelopeKind,
    ChannelPayload,
)

__all__ = [
    "ChannelError",
    "ChannelEndpoint",
    "ChannelDelivery",
    "ChannelDeliveryListener",
    "ChannelEnvelope",
    "ChannelEnvelopeKind",
    "ChannelEventDelivery",
    "ChannelJsonProjectionError",
    "ChannelHost",
    "ChannelHostPort",
    "ChannelOperationAccepted",
    "ChannelOperationCancelRequest",
    "ChannelOperationCancelled",
    "ChannelOperationRequest",
    "ChannelPayload",
    "ChannelRpcFrame",
    "ChannelRpcFrameKind",
    "ChannelUnsubscribe",
    "ProductHostAction",
    "ProductHostActionType",
    "ProductHostAdapter",
    "ProductHostLifecycle",
    "ProductHostRuntime",
    "ProductHostStreams",
    "ProductHostState",
    "ProductHostStateReader",
    "ProductHostTaskTracker",
    "dispose_product_host",
    "JsonlCommand",
    "JsonlCommandErrorListener",
    "JsonlCommandHost",
    "JsonlCommandHostError",
    "JsonlCommandHostErrorKind",
    "JsonlCommandHostErrorReason",
    "JsonlCommandPort",
    "JsonlCommandHandler",
    "JsonlCommandRoute",
    "JsonlCommandRouter",
    "JsonlUnsupportedCommandHandler",
    "RemoteUiContext",
    "channel_envelope_from_json",
    "channel_envelope_to_json",
    "decode_rpc_jsonl_frame",
    "encode_rpc_jsonl_frame",
    "project_channel_value",
    "dispatch_product_host_action",
    "normalize_product_host_action",
    "rpc_jsonl_frame_from_json",
    "rpc_jsonl_frame_to_json",
    "flush_raw_stdout",
    "is_stdout_taken_over",
    "restore_stdout",
    "stdout_guard",
    "take_over_stdout",
    "write_raw_stdout",
]
