"""Product-neutral technical control contracts for multi-agent collaboration."""

from .context import (
    AgentApprovalEnvelope,
    ApprovalExitPort,
    ForkedHistory,
    ForkHistoryDiagnostic,
    ForkTier,
    MappedHistoryMessage,
    SubagentApprovalResolver,
    SubagentContextFactory,
    SubagentContextPlan,
    TranscriptWatermark,
)
from .control import DefaultAgentAuthorityPolicy, MultiAgentControl
from .executor import (
    ImmediateRecipeExecutor,
    RecipeExecutionError,
    RecipeExecutionResult,
    RecipeRunRequest,
)
from .recipes import (
    CollaborationRecipe,
    CollaborationRecipeCatalog,
    RecipeRole,
    core_recipe_catalog,
)
from .registry import AgentRegistry, AgentReservation
from .run_handle import (
    HandleCloseResult,
    HandleDeliveryOutcome,
    SubagentRoundDriver,
    SubagentRoundResult,
    SubagentRunHandle,
)
from .types import (
    AgentAuthorityPolicy,
    AgentCaller,
    AgentCompletionNotice,
    AgentFact,
    AgentInputMessage,
    AgentPath,
    AgentProgress,
    AgentRecord,
    AgentRef,
    AgentTransition,
    AgentTypeRegistry,
    AgentTypeSpec,
    AgentUsage,
    ControlCaller,
    ControlLimits,
    DeliveryIntent,
    HostCaller,
    MultiAgentError,
    TerminalPayload,
)
from .workspace import (
    WorkspaceLease,
    WorkspaceLeasePort,
    WorkspaceLeaseRequest,
    WorkspaceLeaseSnapshot,
    WorkspaceMode,
)

__all__ = [
    "AgentAuthorityPolicy",
    "AgentApprovalEnvelope",
    "AgentCaller",
    "AgentCompletionNotice",
    "AgentFact",
    "AgentInputMessage",
    "AgentPath",
    "AgentProgress",
    "AgentRecord",
    "AgentRef",
    "AgentRegistry",
    "AgentReservation",
    "AgentTransition",
    "AgentTypeRegistry",
    "AgentTypeSpec",
    "AgentUsage",
    "ApprovalExitPort",
    "ControlCaller",
    "ControlLimits",
    "CollaborationRecipe",
    "CollaborationRecipeCatalog",
    "DefaultAgentAuthorityPolicy",
    "DeliveryIntent",
    "ForkHistoryDiagnostic",
    "ForkTier",
    "ForkedHistory",
    "HostCaller",
    "HandleCloseResult",
    "HandleDeliveryOutcome",
    "ImmediateRecipeExecutor",
    "MultiAgentControl",
    "MultiAgentError",
    "MappedHistoryMessage",
    "RecipeExecutionError",
    "RecipeExecutionResult",
    "RecipeRole",
    "RecipeRunRequest",
    "SubagentContextFactory",
    "SubagentContextPlan",
    "SubagentApprovalResolver",
    "SubagentRoundDriver",
    "SubagentRoundResult",
    "SubagentRunHandle",
    "TerminalPayload",
    "TranscriptWatermark",
    "WorkspaceLease",
    "WorkspaceLeasePort",
    "WorkspaceLeaseRequest",
    "WorkspaceLeaseSnapshot",
    "WorkspaceMode",
    "core_recipe_catalog",
]
