from loushang.coding.extensions.api import ExtensionAPI
from loushang.coding.extensions.loader import ExtensionLoader
from loushang.coding.extensions.policy import (
    ExtensionPolicyDecision,
    policy_from_manifest,
)
from loushang.coding.extensions.runner import ExtensionRunner
from loushang.harness.extensions.context import (
    ExtensionCommandContext,
    ExtensionContext,
    ExtensionRuntimeBindings,
    ReplacedSessionContext,
    SessionActionDecision,
    SessionBeforeCompactEvent,
    SessionBeforeCompactResult,
    SessionBeforeForkEvent,
    SessionBeforeForkResult,
    SessionBeforeSwitchEvent,
    SessionBeforeTreeEvent,
    SessionBeforeTreeResult,
    SessionRefreshEvent,
    SessionShutdownEvent,
    SessionStartEvent,
)
from loushang.harness.extensions.contributions import (
    ContributionDescriptor,
    ContributionRegistry,
    DuplicateContributionKeyError,
    DuplicateExtensionSurfaceKeyError,
    ExtensionInventory,
    ExtensionSurfaceDescriptor,
    ExtensionSurfaceType,
    surfaces_from_loaded_extension,
)
from loushang.harness.extensions.events import VALID_EXTENSION_EVENTS
from loushang.harness.extensions.manifest import (
    ExtensionDependencyDeclaration,
    ExtensionHookDeclaration,
    ExtensionManifest,
    ExtensionManifestParseResult,
    ExtensionPermissionDeclaration,
    parse_extension_manifest,
)
from loushang.harness.extensions.types import (
    BeforeAgentStartResult,
    ContextResult,
    ExtensionResourceContribution,
    InputEvent,
    InputEventResult,
    InputSource,
    LoadedExtension,
    RegisteredCommand,
    RegisteredFlag,
    RegisteredShortcut,
    ResolvedCommand,
    ResolvedFlag,
    ResolvedShortcut,
    ToolCallDecision,
    ToolResultDecision,
)
from loushang.harness.resources.source import SourceInfo

__all__ = [
    "BeforeAgentStartResult",
    "ContextResult",
    "ContributionDescriptor",
    "ContributionRegistry",
    "DuplicateContributionKeyError",
    "DuplicateExtensionSurfaceKeyError",
    "ExtensionAPI",
    "ExtensionContext",
    "ExtensionCommandContext",
    "ExtensionDependencyDeclaration",
    "ExtensionHookDeclaration",
    "ReplacedSessionContext",
    "ExtensionLoader",
    "ExtensionManifest",
    "ExtensionManifestParseResult",
    "ExtensionPermissionDeclaration",
    "ExtensionPolicyDecision",
    "ExtensionResourceContribution",
    "ExtensionRuntimeBindings",
    "ExtensionInventory",
    "ExtensionSurfaceDescriptor",
    "ExtensionSurfaceType",
    "InputEvent",
    "InputEventResult",
    "InputSource",
    "ExtensionRunner",
    "LoadedExtension",
    "RegisteredCommand",
    "RegisteredFlag",
    "RegisteredShortcut",
    "ResolvedCommand",
    "ResolvedFlag",
    "ResolvedShortcut",
    "SourceInfo",
    "SessionActionDecision",
    "SessionBeforeCompactEvent",
    "SessionBeforeCompactResult",
    "SessionBeforeForkEvent",
    "SessionBeforeForkResult",
    "SessionBeforeSwitchEvent",
    "SessionBeforeTreeEvent",
    "SessionBeforeTreeResult",
    "SessionRefreshEvent",
    "SessionShutdownEvent",
    "SessionStartEvent",
    "surfaces_from_loaded_extension",
    "ToolCallDecision",
    "ToolResultDecision",
    "VALID_EXTENSION_EVENTS",
    "parse_extension_manifest",
    "policy_from_manifest",
]
