"""Coding-specific extension records and Harness-owned extension exports."""

from __future__ import annotations

from loushang.harness.extensions.context import (
    ExtensionCommandContext,
    ExtensionContext,
    ExtensionRuntimeBindings,
    ReplacedSessionContext,
    SessionActionDecision,
    SessionBeforeCompactEvent,
    SessionBeforeCompactResult,
    SessionBeforeForkEvent,
    SessionBeforeForkResult,
    SessionBeforeSwitchEvent,
    SessionBeforeTreeEvent,
    SessionBeforeTreeResult,
    SessionRefreshEvent,
    SessionShutdownEvent,
    SessionStartEvent,
)
from loushang.harness.extensions.events import VALID_EXTENSION_EVENTS
from loushang.harness.extensions.types import (
    BeforeAgentStartResult,
    ContextResult,
    ExtensionHandler,
    ExtensionResourceContribution,
    InputEvent,
    InputEventResult,
    InputSource,
    LoadedExtension,
    RegisteredCommand,
    RegisteredFlag,
    RegisteredShortcut,
    ResolvedCommand,
    ResolvedFlag,
    ResolvedShortcut,
    ToolCallDecision,
    ToolResultDecision,
)
from loushang.harness.resources.source import SourceInfo

__all__ = [
    "BeforeAgentStartResult",
    "ContextResult",
    "ExtensionContext",
    "ExtensionCommandContext",
    "ReplacedSessionContext",
    "ExtensionHandler",
    "ExtensionResourceContribution",
    "ExtensionRuntimeBindings",
    "InputEvent",
    "InputEventResult",
    "InputSource",
    "LoadedExtension",
    "RegisteredCommand",
    "RegisteredFlag",
    "RegisteredShortcut",
    "ResolvedCommand",
    "ResolvedFlag",
    "ResolvedShortcut",
    "SourceInfo",
    "SessionActionDecision",
    "SessionStartEvent",
    "SessionShutdownEvent",
    "SessionBeforeCompactEvent",
    "SessionBeforeForkEvent",
    "SessionBeforeCompactResult",
    "SessionBeforeForkResult",
    "SessionBeforeSwitchEvent",
    "SessionBeforeTreeEvent",
    "SessionBeforeTreeResult",
    "SessionRefreshEvent",
    "ToolCallDecision",
    "ToolResultDecision",
    "VALID_EXTENSION_EVENTS",
]
